# Generated by Django 5.1.3 on 2025-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MAIN", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                default="project_photos/default-project.png",
                null=True,
                upload_to="project_photos/",
            ),
        ),
    ]
